### ISSUE TITLE
Speed things up with option of minimum window size

### ISSUE THREAD

**Issue by danielrosenbloom** [RabadanLab/TARGet#8]
Right now the -s flag specifies the maximum window size; TARGet tries all smaller window sizes. But maybe the user doesn't always care about perfect optimization and just wants a fixed window size, or doesn't want to bother with windows of size 2 or 3. Cutting down on the # of windows used will speed things up.

**Comment by pcamara** [comment]
That's a nice feature. I will implement it soon. I close this, as a similar proposal by Kevin is still open.
